<h1><?= ucfirst($this->escapeHtml($this->category)); ?></h1>

<?php if ($this->listings instanceof Zend\Db\ResultSet\ResultSet): ?>

<table class="table">
    <thead>
    <tr>
        <th>Title</th>
        <th>Price</th>
        <th>Date Created</th>
        <th>Date Expires</th>
        <th>City</th>
        <th>Country</th>
    </tr>
    </thead>
    <tbody>
    <?php while ($item = $this->listings->current()): ?>
    <?php /* We could use the table-striped from bootstrap at table, but we will use the cycle() view helper as an example. */ ?>
    <tr style="background-color: <?php echo $this->cycle(array('#F9F9F9', '#FFFFFF'))->next(); ?>">
        <td>
            <a href="<?php echo $this->url('market/view/item') . $item['listings_id']; ?>">
                <?php echo $this->escapehtml($item['title']); ?>
            </a>
        </td>
        <td><?php echo $this->escapehtml((float) $item['price']); ?></td>
        <td><?php echo $this->escapehtml($item['date_created']); ?></td>
        <td><?php echo $this->escapehtml($item['date_expires']); ?></td>
        <td><?php echo $this->escapehtml($item['city']); ?></td>
        <td><?php echo $this->escapehtml($item['country']); ?></td>
    </tr>
    <?php $this->listings->next(); ?>
    <?php endwhile; ?>
    </tbody>
</table>
<?php else: ?>
<?php Zend\Debug\Debug::dump($this->listings); ?>
<?php endif; ?>
